name: gatk-snp-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.6
  - pyyaml>=5.1.0
  - setuptools>=42.0.0
  - wheel>=0.37.0
  - psutil>=5.8.0
  - typing-extensions>=3.7.4
  - pathlib>=1.0.1
  - argparse>=1.4.0
  - pyinstaller>=4.5.0
  - pytest>=6.2.5
  - pytest-cov>=2.12.0
  - pytest-mock>=3.6.0
  - black>=21.5b2
  - flake8>=3.9.0
  - mypy>=0.910
  - isort>=5.9.0
  - sphinx>=4.0.0
  - sphinx-rtd-theme>=0.5.0
  - recommonmark>=0.7.0
  - numpy>=1.19.0
  - pandas>=1.2.0
  - matplotlib>=3.3.0
  # 生物信息学软件
  - gatk4
  - bwa
  - samtools
  - picard
  - vcftools
  - bgzip
  - tabix
  - fastp
  - qualimap
  - multiqc
  - pip
  - pip:
    - bwa-mem2  # 需要手动安装的软件 