gatk:
  min_allele_fraction: 0.2
  min_base_quality: 20
max_memory: 32
memory_per_thread: 2
output_dir: path/to/output
performance:
  auto_optimize: true
  parallel_jobs: 3
quality_control:
  min_base_quality: 20
  min_mapping_quality: 30
reference: path/to/reference.fasta
samples_dir: path/to/samples
software_paths:
  bcftools: path/to/bcftools
  bwa: path/to/bwa
  bwa-mem2: path/to/bwa-mem2
  fastp: path/to/fastp
  gatk: path/to/gatk
  multiqc: path/to/multiqc
  picard: path/to/picard
  qualimap: path/to/qualimap
  samtools: path/to/samtools
  vcftools: path/to/vcftools
threads: 8
