# GATK SNP Calling Pipeline默认配置

# 路径配置
samples_dir: "path/to/your/samples"        # 测序数据所在目录
output_dir: "path/to/your/output"          # 输出结果目录
reference_genome: "path/to/reference.fasta" # 参考基因组路径

# 性能配置
threads_per_job: 8                         # 每个任务使用的线程数
max_parallel_jobs: 3                       # 最大并行任务数
max_memory: 32                            # 最大内存使用量(GB)

# 任务优先级配置
priority_map:                              # 任务优先级映射，数字越大优先级越高
  ref_index: 10                           # 参考基因组索引
  bwa_map: 5                              # BWA比对
  sort_sam: 4                             # 排序SAM文件
  mark_duplicates: 4                      # 标记重复序列
  index_bam: 3                            # 索引BAM文件
  haplotype_caller: 5                     # GATK HaplotypeCaller
  combine_gvcfs: 4                        # 合并GVCF文件
  genotype_gvcfs: 4                       # 基因型分型
  vcf_filter: 3                           # VCF过滤
  select_snp: 3                           # 选择SNP
  soft_filter_snp: 3                      # SNP软过滤
  get_gwas_data: 2                        # 获取GWAS数据

# BWA映射参数
bwa_params: "-R '@RG\\tID:{sample}\\tLB:{sample}\\tPL:illumina\\tSM:{sample}'"

# GATK参数
gatk_java_options: "-Xmx4g -Xms2g -XX:ParallelGCThreads=2"
gatk_haplotype_caller_params: "--pcr-indel-model CONSERVATIVE -ERC GVCF"
gatk_genotype_gvcfs_params: "--max-alternate-alleles 2"
gatk_variant_filtration_params: "--filter-expression 'QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0 || SOR > 3.0' --filter-name 'hard_filter'"

# SNP软过滤参数（使用vcftools）
snp_soft_filter_max_missing: 0.2           # 最大缺失率
snp_soft_filter_maf: 0.05                  # 最小次等位基因频率
snp_soft_filter_geno: 0.1                  # 最大基因型缺失率

# 文件名模式
fastq_pattern: "_clean_{read}.fastq.gz"    # 原始数据文件名模式，{read}将被替换为1或2
clean_pattern: "_clean"                    # 样本名中需要去除的部分