name: Build Executables

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        conda install -c bioconda -c conda-forge mamba
        mamba install -c bioconda -c conda-forge gatk4 bwa samtools picard vcftools bgzip tabix fastp qualimap multiqc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Create dist directory
      run: mkdir -p dist
    - name: Build Windows executable
      run: python build.py
    - name: Check executable
      run: |
        if (!(Test-Path dist/gatk-snp-pipeline-windows-x64.exe)) {
          Write-Error "Windows executable not found"
          exit 1
        }
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/gatk-snp-pipeline-windows-x64.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        conda install -c bioconda -c conda-forge mamba
        mamba install -c bioconda -c conda-forge gatk4 bwa samtools picard vcftools bgzip tabix fastp qualimap multiqc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Create dist directory
      run: mkdir -p dist
    - name: Build Linux executable
      run: python build.py
    - name: Check executable
      run: |
        if [ ! -f dist/gatk-snp-pipeline-linux-x64 ]; then
          echo "Linux executable not found"
          exit 1
        fi
        chmod +x dist/gatk-snp-pipeline-linux-x64
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-exe
        path: dist/gatk-snp-pipeline-linux-x64

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        conda install -c bioconda -c conda-forge mamba
        mamba install -c bioconda -c conda-forge gatk4 bwa samtools picard vcftools bgzip tabix fastp qualimap multiqc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Create dist directory
      run: mkdir -p dist
    - name: Build macOS executable
      run: python build.py
    - name: Check executable
      run: |
        if [ ! -f dist/gatk-snp-pipeline-darwin-x64 ]; then
          echo "macOS executable not found"
          exit 1
        fi
        chmod +x dist/gatk-snp-pipeline-darwin-x64
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-exe
        path: dist/gatk-snp-pipeline-darwin-x64

  release:
    needs: [build-windows, build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-exe/gatk-snp-pipeline-windows-x64.exe
          linux-exe/gatk-snp-pipeline-linux-x64
          macos-exe/gatk-snp-pipeline-darwin-x64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 